#cloud-config
package_update: true
packages:
  - ca-certificates
  - curl
  - gnupg
  - apt-transport-https
  - software-properties-common
runcmd:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
  - sudo apt-get install ca-certificates curl gnupg 
  - sudo install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - sudo chmod a+r /etc/apt/keyrings/docker.gpg
  - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - apt-get install -y git
  - git clone [YOUR_APPWRITE_DOCKERCOMPOSE_AND_.ENV_FILE_FROM_GIT_REPO] /home/root/appwrite
  - sudo DEBIAN_FRONTEND=noninteractive apt install docker-compose -y
  - cd /home/root/appwrite && docker-compose up -d
  - docker compose exec appwrite ssl
